# fly.toml app configuration file generated for waterweb-cold-river-5929 on 2023-12-05T02:01:47+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "waterweb-cold-river-5929"
primary_region = "nrt"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[services]]
internal_port = 8080
protocol = "tcp"

[[services.ports]]
port = "80"
